apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-vm
  namespace: default
spec:
  containers:
    - name: ubuntu-vm
      image: ubuntu:latest
      command:
        - bash
        - "-c"
        - |
          
          # install the required packages
          apt update -y
          apt install python3 openssh-server nginx
          
          # create the ansible user and change the password
          useradd -m ansible
          echo "ansible:<password>" | chpasswd
          
          # update the /etc/sshd/ssh_config to accept password login
          sed -i 's/^#PasswordAuthentication no/PasswordAuthentication yes/' /etc/sshd/ssh_config
          
          # start the nginx
          /usr/sbin/nginx
          
          # run the process
          /usr/sbin/sshd -D
          
