all:
  children:
    ubuntulab:
      hosts:
        ubuntulab0101:
          ansible_host: 127.0.0.1
          ansible_port: 2221
        ubuntulab0102:
          ansible_host: 127.0.0.1
          ansible_port: 2222
        ubuntulab0103:
          ansible_host: 127.0.0.1
          ansible_port: 2223
